version: "3.5"
services:
  orion:
    image: fiware/orion-ld
    hostname: orion${SUFFIX}
    container_name: fiware-orion${SUFFIX}
    expose:
      - "1026"
    ports:
      - "${PORT}:1026"

    depends_on:
      - mongo-db
    command: -dbhost mongo-db${SUFFIX} -logLevel DEBUG -mongocOnly -wip entityMaps,distSubs -forwarding
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db${SUFFIX}
    container_name: db-mongo${SUFFIX}
    ports:
      - "${DB_PORT}:27017"
    networks:
      - default
    command: --nojournal
    volumes:
      - mongo-db:/data

volumes:
  mongo-db: ~
