# see possible config : https://mosquitto.org/man/mosquitto-conf-5.html
allow_anonymous false
listener 1883
# file with username user:user_with_password and password:password
password_file /mosquitto/config/mosquitto_pwd