# The different types of validation to support. These values are reflected in other properties.
validator.type = Custom
validator.externalSchemas.Custom = optional

# Translations
validator.locale.default = en
validator.locale.translations = translations